export const GET_ERRORS = "GET_ERRORS";
export const GET_TODOLISTS = "GET_TODOLISTS";
export const GET_TODOLIST = "GET_TODOLIST";
export const DELETE_TODOLIST = "DELETE_TODOLIST";


export const GET_TODOLIST_TASKS = "GET_TODOLIST_TASKS";
export const GET_TODOLIST_TASK = "GET_TODOLIST_TASK";
export const DELETE_TODOLIST_TASK = "DELETE_TODOLIST_TASK";
export const UPDATE_TODOLIST_TASK = "UPDATE_TODOLIST_TASK";
